In [1]:
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:Postg_anderzon@localhost:5432/ventas_dw')
folder = Path('../data_sets')

In [2]:
dfs = {}

for fl in folder.glob('*parquet'):
    df = f'df_{fl.stem}'
    dfs[df] = pd.read_parquet(fl)

print('Los dataset cargados fueron: \n')
print(dfs.keys())

Los dataset cargados fueron:

dict_keys(['df_cargo', 'df_categoria', 'df_cliente', 'df_compras', 'df_edad_cliente', 'df_empleado', 'df_forma_pago', 'df_nivel_cliente', 'df_productos', 'df_region', 'df_tienda', 'df_ventas'])

In [9]:
dfs['df_cargo']['id_cargo'].count()

np.int64(9)

In [9]:
resumen = []

for nombre, df in dfs.items():
    resumen.append({
        "tabla": nombre,
        "filas": df.shape[0]-1,
        "columnas": df.shape[1],
        "nulos_totales": df.isna().sum().sum(),
        "memoria_MB": round(df.memory_usage(deep=True).sum() / 1024**2, 2),
        "duplicados": df.duplicated().sum(),
        "nulos_totales": df.isna().sum().sum()
    })

df_resumen = pd.DataFrame(resumen)
print (f'Tabla de resumen: ')
df_resumen

Tabla de resumen:

               tabla  filas  columnas  nulos_totales  memoria_MB  duplicados
0           df_cargo      8         3              0        0.00           0
1       df_categoria     14         3              0        0.00           0
2         df_cliente     29         5              0        0.00           0
3         df_compras     39         8              0        0.00           0
4    df_edad_cliente      4         4              0        0.00           0
5        df_empleado     19         8              0        0.00           0
6      df_forma_pago      4         2              0        0.00           0
7   df_nivel_cliente      4         4              0        0.00           0
8       df_productos     74         4              0        0.00           0
9          df_region     14         3              0        0.00           0
10         df_tienda      3         4              0        0.00           0
11         df_ventas     99         8              0        0.01           0

In [10]:
def normalizar_empleados (fds, ruta):
    
    dimempleado = (dfs['df_empleado']
               .merge(dfs['df_cargo'])
               .merge(dfs['df_tienda'])
               )

    dimempleado = dimempleado.drop(columns=['id_cargo', 'id_tienda', 'salario_mensual', 'codigo_tienda', 'id_region'])

    dimempleado.to_parquet(
    '../DW_bd/dimempleado.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy'
    )
    
    print (f'almacenado en: {ruta}')

    return None

In [11]:
normalizar_empleados(dfs, folder)

almacenado en: ..\data_sets

In [12]:
def normalizar_clientes (fds, ruta):
    
    df = (dfs['df_cliente']
               .merge(dfs['df_edad_cliente'], on='id_tipo_cliente')
               .merge(dfs['df_nivel_cliente'], on='id_nivel_cliente')
               )

    df = df.drop(columns=['id_tipo_cliente', 'id_nivel_cliente', 'requerimiento_anual'])

    df.to_parquet(
    '../DW_bd/dimcliente.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy'
    )
    
    print (f'almacenado en: {ruta}')

    return None

In [13]:
normalizar_clientes(dfs,folder)

almacenado en: ..\data_sets

In [14]:
def normalizar_forma_pago (fds, ruta):

    df = dfs['df_forma_pago']

    df.to_parquet(
    '../DW_bd/dimforma_pago.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy'
    )
    
    print (f'almacenado en: {ruta}')

    return None

In [15]:
normalizar_forma_pago(df,folder)

almacenado en: ..\data_sets

In [16]:
def normalizar_producto (fds, ruta):
    
    df = (dfs['df_productos']
               .merge(dfs['df_categoria'], on='id_categoria')
               )

    df = df.drop(columns=['id_categoria', 'descripcion'])

    df.to_parquet(
    '../DW_bd/dimproducto.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy'
    )
    
    print (f'almacenado en: {ruta}')

    return None

In [17]:
normalizar_producto (dfs, folder)

almacenado en: ..\data_sets

In [18]:
def normalizar_tienda (fds, ruta):
    
    df = (dfs['df_tienda']
               .merge(dfs['df_region'], on='id_region')
               )

    df = df.drop(columns=['id_region','codigo_iso'])

    df.to_parquet(
    '../DW_bd/dimtienda.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy'
    )
    
    print (f'almacenado en: {ruta}')

    return None

In [19]:
normalizar_tienda(dfs,folder)

almacenado en: ..\data_sets

In [20]:
def normalizar_compras (fds, ruta):
    
    df = (dfs['df_compras']
               .merge(dfs['df_productos'], on='id_producto')
               )

    df = df.drop(columns=['stock','id_categoria'])

    df.to_parquet(
    '../DW_bd/dimcompras.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy'
    )
    
    print (f'almacenado en: {ruta}')

    return None

In [21]:
folder_dw = Path('../DW_bd')
dfs_ehcos = {}

for fl in folder_dw.glob('*parquet'):
    df = f'df_{fl.stem}'
    dfs_ehcos[df] = pd.read_parquet(fl)

print('Los dataset cargados fueron: \n')
print(dfs_ehcos.keys())

Los dataset cargados fueron:

dict_keys(['df_dimcliente', 'df_dimcompras', 'df_dimempleado', 'df_dimforma_pago', 'df_dimproducto', 'df_dimtienda', 'df_echos'])

In [22]:
#verificar integridad referencial
dfs['df_ventas']['id_cliente'].isin(dfs_ehcos['df_dimcliente']['id_cliente']).all()

np.True_

In [23]:
def normalizar_ventas (dfs_1, ruta):

    compras = dfs_ehcos['df_dimcompras'][['id_compra','id_producto']]

    df = (dfs['df_ventas']
               .merge(compras, on='id_producto', how= 'left')
               )

    df.to_parquet(
    '../DW_bd/echos.parquet',
    engine='pyarrow',
    index=False,
    compression='snappy'
    )
    df
    print (f'almacenado en: {ruta}')

    return df

In [24]:
normalizar_ventas(dfs, folder)

almacenado en: ..\data_sets

,id_venta,id_cliente,id_producto,cantidad,fecha_compra,id_tienda,id_empleado,id_forma_pago,id_compra
0,1,5,12,2,01/01/2015,1,5,1,12.0
1,2,14,45,1,01/01/2015,2,14,2,NaN
2,3,22,3,3,02/01/2015,3,11,3,3.0
3,4,8,67,1,02/01/2015,4,4,4,35.0
4,5,30,21,2,03/01/2015,1,13,5,16.0
...,...,...,...,...,...,...,...,...,...
95,96,8,11,4,18/01/2015,4,16,1,11.0
96,97,3,66,1,23/01/2015,1,9,2,34.0
97,98,18,43,2,27/01/2015,2,18,3,NaN
98,99,11,27,1,31/01/2015,3,3,4,19.0
99,100,25,52,1,15/01/2015,4,20,5,29.0